all:makefiles

makefiles: calculator project.c
gcc -wall -o makefiles calculator project.c
calculator project.c: function files.c
gcc -c- wall function files.c
function files.c: function files1.c
gcc -c- wall function files1.c
function files1.c: function files2.c
gcc -c- wall function files2.c
 
